### ISSUE TITLE
Publish a version with Vite 3 as a dependency

### ISSUE THREAD

**Issue by jods4** [meowtec/vite-plugin-svg-sprite#10]
This plugin has a dependency on `Vite@2` so it can't be installed without `--force` after upgrading to Vite 3.

FWIW it seems to work perfectly fine in my project, didn't notice any issue. It's probably just a matter of changing the dependency range in `project.json`.

**Comment by meowtec** [comment]
fixed in vite-plugin-svg-sprite@0.2.4

**Comment by jods4** [comment]
Thanks!
