### ISSUE TITLE
createSvgSpritePlugin is not a function

### ISSUE THREAD

**Issue by Hrishikesh-K** [meowtec/vite-plugin-svg-sprite#11]
Hi!

I'm trying to use this plugin in a Vue 3 TS + Vite 3 project, but it appears to be failing at the initial step. `npm run dev` fails with the above mentioned error. Here's a demo: https://stackblitz.com/edit/vitejs-vite-du7xik

**Comment by meowtec** [comment]
Fixed on vite-plugin-svg-sprite@0.2.6

**Comment by Hrishikesh-K** [comment]
Seems to work! Thanks a lot!
