### ISSUE TITLE
Add exports of SVG attributes

### ISSUE THREAD

**Issue by illright** [meowtec/vite-plugin-svg-sprite#16]
I have several kinds of SVGs in my project: most are icons, but some are pictograms with certain dimensions. Those SVGs are exported from Figma, so the correct dimensions are baked into the SVGs through the `width` and `height` attributes. I would like to access those attributes by importing them as named exports from the SVG file.

It could look like this:
```tsx
import symbolPictogram404, { width, height } from "./pictogram-404.svg";

function Pictogram404() {
  return (
    <svg width={width} height={height}>
      <use href={`#${symbolPictogram404}`} />
    </svg>
  );
}
```

Since it slightly changes the exports of an `*.svg` module, we would also have to provide a [declaration helper](https://github.com/pd4d10/vite-plugin-svgr#usage) like SVGR does.

Is it something you would accept as a PR?

**Comment by meowtec** [comment]
I seems nice, PR welcome.
