### ISSUE TITLE
Update dependencies to resolve multiple CVE's

### ISSUE THREAD

**Issue by mariuswg** [meowtec/vite-plugin-svg-sprite#27]
We have identified two critical CVEs in the current version of micromatch, because we use vite-plugin-svg-sprite in our project. To address these vulnerabilities, please update micromatch to version 4.0.8. This issue was detected via Dependabot. I have no relation to micromatch and this issue is purely reported for solidarity.

When I cloned your repository and checked for vulnerabilites with `npm audit` i got the following output:
```
# npm audit report

braces  <3.0.3
Severity: high
Uncontrolled resource consumption in braces - https://github.com/advisories/GHSA-grv7-fg5c-xmjg
fix available via `npm audit fix --force`
Will install svg-baker@1.2.13, which is a breaking change
node_modules/svg-baker/node_modules/braces
  micromatch  <=4.0.7
  Depends on vulnerable versions of braces
  node_modules/svg-baker/node_modules/micromatch
    svg-baker  >=1.2.5
    Depends on vulnerable versions of micromatch
    Depends on vulnerable versions of postcss
    node_modules/svg-baker


postcss  <=8.4.30
Severity: moderate
Regular Expression Denial of Service in postcss - https://github.com/advisories/GHSA-566m-qj78-rww5
PostCSS line return parsing error - https://github.com/advisories/GHSA-7fh5-64p2-3v2j
fix available via `npm audit fix --force`
Will install svg-baker@1.2.13, which is a breaking change
node_modules/postcss

4 vulnerabilities (2 moderate, 2 high)

To address all issues (including breaking changes), run:
  npm audit fix --force
```

I considered running the `npm audit fix --force` command and creating a Pull Request. However, to avoid any potential disruptions following breaking changes, I decided to leave this task for you. This command appears to update both the micromatch and svg-baker dependencies, as svg-baker has its own dependencies.

For more details, refer to the [micromatch v4.0.8 release notes](https://github.com/micromatch/micromatch/releases/tag/4.0.8).

**Comment by meowtec** [comment]
Has been resolved, thank you.
